server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tmall?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimumIdle: 1
      connectionTimeout: 60000
  jpa:
      show-sql: true
  #    open-in-view: true
      database-platform: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        use-new-id-generator-mappings: true